--- 
abstract: Allows RT to do authentication via PAUSE (pause.perl.org)
author: 
  - Thomas Sibley <trs@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.68
license: GPL version 2
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RT-Authen-PAUSE
no_index: 
  directory: 
    - html
    - inc
    - t
requires: 
  HTTP::Request: 0
  LWP::UserAgent: 0
version: 0.02
